<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>TOEFL Junior</title>
  <style>
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: Arial, sans-serif;
      background-color: #fff;
      color: #000;
      margin: 20px;
    }

    .score-report {
      max-width: 800px;
      margin: 0 auto;
      border: 2px solid #000;
      padding: 20px;
      position: relative;
    }

    /* Header */
    .report-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 20px;
    }
    .report-header .logo {
      height: 40px;
    }
    .report-header .report-title {
      font-size: 1.4rem;
      font-weight: bold;
      text-transform: uppercase;
    }

    /* Informasi Peserta */
    .info-section {
      display: flex;
      justify-content: space-between;
      margin-bottom: 20px;
    }
    .info-left {
      width: 60%;
    }
    .info-left p {
      margin-bottom: 6px;
      line-height: 1.4;
    }
    .info-right {
      width: 35%;
      text-align: right;
    }
    .profile-photo {
      width: 100px;
      height: 120px;
      border: 1px solid #000;
      object-fit: cover;
    }
    /* Garis pemisah */
    .section-divider {
      border: none;
      border-top: 1px solid #000;
      margin: 10px 0;
    }
    /* Bagian Skor */
    .scores-section {
      margin-bottom: 20px;
    }
    .scores-title {
      font-size: 1.2rem;
      font-weight: bold;
      margin-bottom: 10px;
      text-transform: uppercase;
    }
    .score-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 10px;
    }
    .score-table th,
    .score-table td {
      border: 1px solid #000;
      padding: 8px;
      text-align: center;
    }
    .score-table th {
      background-color: #f0f0f0;
    }
    .notes {
      font-size: 0.9rem;
      color: #555;
      margin-top: 5px;
      line-height: 1.4;
    }

    /* Bagian QR */
    .qr-section {
      text-align: center;
      margin-top: 20px;
    }
    .qr-section p {
      margin-bottom: 10px;
      font-weight: bold;
    }

    /* Footer */
    .report-footer {
      text-align: center;
      font-size: 0.8rem;
      margin-top: 20px;
      color: #555;
    }
  </style>
</head>
<body>

  <div class="score-report">
    <!-- Bagian Header -->
    <div class="report-header">
      <!-- Logo TOEFL -->
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/ETS_Logo.svg/2560px-ETS_Logo.svg.png" 
           alt="Logo" class="logo">
      <div class="report-title">IELTS Test Prediction C</div>
    </div>

    <!-- Informasi Peserta (kiri: data siswa, kanan: foto) -->
    <div class="info-section">
      <div class="info-left">
        <p><strong>Name:</strong> {{ $certificateieltstestc->name }}</p>
        <p><strong>Class:</strong> {{ $certificateieltstestc->class }}</p>
        <p><strong>Appointment Number:</strong> 123456789</p>
        <p><strong>Test Date:</strong> {{ $certificateieltstestc->exam_date }}</p>
        <p><strong>Gender:</strong> Male/Female</p>
        <p><strong>Date of Birth:</strong> 01/01/1990</p>
        <p><strong>Registration Number:</strong> REG-987654321</p>
      </div>
      <div class="info-right">

        <p>SMA BPI</p>
      </div>
    </div>

    <hr class="section-divider">

    <!-- Bagian Skor -->
    <div class="scores-section">
      <div class="scores-title">Test Date Scores</div>
      <table class="score-table">
        <thead>
          <tr>
            <th>Reading</th>
            <th>Listening</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ $certificateieltstestc->reading_score }} / 30</td>
            <td>{{ $certificateieltstestc->listening_score }} / 30</td>
            <td>{{ $certificateieltstestc->total_score }} / 120</td>
          </tr>
        </tbody>
      </table>
      <div class="notes">
        <p>*Scores reflect performance on the test date listed above.</p>
        <p>*Scores are reported on a 0–30 scale for each section; total 0–120.</p>
      </div>
    </div>

    <!-- Bagian QR -->
    <div class="qr-section">
      <p>Scan to Verify</p>
      {!! $qrCode !!}
    </div>

    <!-- Footer -->
    <div class="report-footer">
      <p>© 2025 Educational Testing Service (ETS). All rights reserved.</p>
      <p>This is a sample TOEFL iBT Score Report, generated by your system.</p>
    </div>
  </div>

</body>
</html>
